name: "Deploy Pages"

on:
  workflow_dispatch:

jobs:
  make-report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy Static Site
        run: |
          rm report/*
          mkdir -p report
          python src/export_pages.py
          mv index.html report/index.html
          mv details.html report/details.html
      - name: Setup Pages
        if: github.ref == 'refs/head/main'
        uses: actions/configure-pages@v3

      - name: Upload Artifcat
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./report"

  deploy-report:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: make-report

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2


